### ISSUE TITLE
Support Include and Select

### ISSUE THREAD

**Issue by omar-dulaimi** [omar-dulaimi/prisma-trpc-generator#13]
### Discussed in https://github.com/omar-dulaimi/prisma-trpc-generator/discussions/11

This requires work to be done here in this library and also in `Prisma Zod Generator`.

**Comment by konuch** [comment]
Here's a similar package for graphql based on prisma, which you can use as an inspiration: https://github.com/MichalLytek/typegraphql-prisma

**Comment by omar-dulaimi** [comment]
> Any update on this?

Not much time these days unfortunately. Though PRs are welcomed if anybody decided to work on it.

**Comment by kristinlindquist** [comment]
One of the engineers on my team is going to take a crack at this. Assuming success, a PR will be forthcoming!

**Comment by omar-dulaimi** [comment]
`Select` is live with the latest release `0.5.0`. Special thanks to @BitPhoenix

**Comment by vikt0r0** [comment]
🙏

**Comment by vikt0r0** [comment]
I am able to generate the schemas by specifying to the generator to make include and select queries, and I can issue the query, e.g.:

```
const jobsQuery = trpc.project.job.findManyJob.useQuery({
  take: 40,
  include: { employer: true },
});
```

I can see that the queries are made to retrieve the correct data, but how do I access the included data? I can only access the ID, despite my relationships being defined (i.e. they work in prisma studio):

```
{jobsQuery.data?.map((job) => {
  <p>{job.employerId}</p>;
})}
```

Also, previously `job` had type `Job` of the model generated from the Prisma schema. Now it is just `SerializeObject<UndefinedToOptional<Job>>`. What am I doing wrong?

**Comment by zrachlin** [comment]
@omar-dulaimi I'm dealing with the same issue that @vikt0r0 mentioned above - when using include, the type produced by the query doesn't include the linked relations. I'd like to take a stab at a PR, but I'm not really sure where to start. If you could point me in the right direction, hopefully I can figure something out.

Thanks for this package by the way!

**Comment by omar-dulaimi** [comment]
Hey @vikt0r0 @zrachlin 
Please open a new issue with reproducible steps so I can take a look at it. I would appreciate it if you shared a sample schema and prisma version, etc.

**Comment by vikt0r0** [comment]
Sure. I also have a project I can send you if you want me to.
