### ISSUE TITLE
CreateMany generate object schema instead of array schema

### ISSUE THREAD

**Issue by cnf-blueware** [omar-dulaimi/prisma-trpc-generator#21]
### Bug description

Seems like createmany zod schema is generating object schema similar to createone instead of generating the array schema for the data

```
export const CreateManySchema = z.object({
  data: CreateManyInputObjectSchema,
});

```

### Environment & setup

- OS: 
- Database: 
- Node.js version: 

### Prisma Version

```

```

**Comment by omar-dulaimi** [comment]
Hello @cnf-blueware 
Do you have an idea how the working version would look to you?
