### ISSUE TITLE
Missing Aggregate field in schema.

### ISSUE THREAD

**Issue by omar-dulaimi** [omar-dulaimi/prisma-trpc-generator#24]
### Discussed in https://github.com/omar-dulaimi/prisma-trpc-generator/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **Revitate** August  6, 2022</sup>
From prisma document (https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#aggregate)
and generated schema <img width="801" alt="image" src="https://user-images.githubusercontent.com/19814112/183219825-2d78d35d-8f27-4cf0-acd8-f55582023987.png">
I think it has missing field `_count`, `_avg`, `_sum`, `_min` and `_max` in InputSchema.
Can you help me?</div>

**Comment by HananoshikaYomaru** [comment]
![image](https://user-images.githubusercontent.com/43137033/184579330-987346cd-c9a2-4317-81e8-537cd34ef200.png)
I think some router are generating some `undefined` operation. Why does this happens?

**Comment by Revitate** [comment]
@omar-dulaimi
Please check this pull request.
https://github.com/omar-dulaimi/prisma-zod-generator/pull/27

**Comment by omar-dulaimi** [comment]
Released in https://github.com/omar-dulaimi/prisma-trpc-generator/releases/tag/0.4.5

Thank you for working on it. @Revitate
