### ISSUE TITLE
incorrect import permission generated

### ISSUE THREAD

**Issue by cnf-blueware** [omar-dulaimi/prisma-trpc-generator#3]
### Bug description

incorrect generated line in createRouter.ts
`import { permissions } from "undefined/shield";`

![image](https://user-images.githubusercontent.com/104558885/174487043-fa54b740-8fea-463e-ac3e-c1ec3023d484.png)

### How to reproduce

Run npx prisma generate

### Prisma information

generator client {
  provider = "prisma-client-js"
}

generator trpc {
  provider = "prisma-trpc-generator"
  withMiddleware = false
  withShield     = false
  output   = "./trpc"
}

datasource db {
  provider = "sqlite"
  url      = "file:db.sqlite"
}

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?
  posts Post[]
}

model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
}

### Environment & setup

- OS: MacOS
- Database: SQLite
- Node.js version: 16.15.0

### Prisma Version

3.15.2

**Comment by omar-dulaimi** [comment]
Fixed in `0.1.11`
