### ISSUE TITLE
Ability to not generate certain routers

### ISSUE THREAD

**Issue by bring-shrubbery** [omar-dulaimi/prisma-trpc-generator#37]
## Problem

Some of the models created in Prisma schema are not meant to be touched by the frontend at all. As an example, `VerificationToken` from the NextAuth is not something I want to be able to interact with from the client-side - I want to leave it to NextAuth to deal with it.

## Suggested solution

It would be great to be able to disable the generation of a router for the Prisma model by using a simple comment, something like following:

```prisma
// @trpc-ignore
model VerificationToken {
  ...
}
```

I understand that it's not as straightforward as just ignoring the model, since other models might reference the ignored one. In this case, the other model's router should also not include the ignored model, so the property that references it should be removed.

## Alternatives

If this feature already exists, would be nice to have it documented in README

**Comment by bring-shrubbery** [comment]
@omar-dulaimi Seems to work for me. Maybe it would also be useful to add a relation to the hidden "Map" model in the example schema? This would test the hiding of the parameter when it's referenced from somewhere? This would test  Something like this:

```prisma
model Post {
  id        Int      @id @default(autoincrement())
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
  title     String
  content   String?
  published Boolean  @default(false)
  viewCount Int      @default(0)
  author    User?    @relation(fields: [authorId], references: [id])
  authorId  Int?
  likes     BigInt

  books Map[]
}

/// @@tRPCGen.model(hide: true)
model Map {
  key    String @id
  value  String
  Post   Post?  @relation(fields: [postId], references: [id])
  postId Int?
}
```

**Comment by omar-dulaimi** [comment]
Released in https://github.com/omar-dulaimi/prisma-trpc-generator/releases/tag/0.7.0
