### ISSUE TITLE
Option in generator to enable/disable zod schema validation in TRPC routes

### ISSUE THREAD

**Issue by arnm** [omar-dulaimi/prisma-trpc-generator#70]
## Problem

I would like to create the trpc routes from the prisma schema but not use zod schema validation.

## Suggested solution

Have an option in the generator to toggle usage of zod schema validation.

**Comment by omar-dulaimi** [comment]
Released in https://github.com/omar-dulaimi/prisma-trpc-generator/releases/tag/1.2.0

Thanks for the contribution
